import sys


def format_contributors(version):
    """
    Takes in a version matching a markdown file generated by changie in the .changes directory.
    Grabs the contributor info at the end of each change line, pulls it off and puts it all at the
    bottom of this bacth of changes in a contributing section.
    """
    fp = f"../.changes/{version}.md"
    separator = "ContributorData "
    bullet = "-"

    # this is pretty brute force
    core_team = [
        "emmyoop",
        "nathaniel-may",
        "gshank" "leahwicz",
        "ChenyuLInx",
        "stu-k",
        "iknox-fa",
        "VersusFacit",
        "McKnight-42",
        "jtcohen6",
    ]

    contributors = {}
    new_file_contents = ""

    with open(fp, "r+") as f:
        string_list = f.readlines()
        #  pull the contributor info off the end of the lines
        for line in string_list:
            if line[0] == bullet:
                # TODO: handle is this data is blank

                # Ex: `- This is my change text (#1234, #4567) ContributorData userName 4567`
                # first split the line by the changelog contents and the bits we
                # need to generate the contributors sections
                a, b = line.split(separator)

                # split up the contributors section into useful bits
                user, pr = b.split(" ")

                # only non-core team members are part of the contributors section
                if user and user not in core_team:
                    if user in contributors:
                        contributors[user].append(pr.strip("\n"))
                    else:
                        contributors[user] = [pr.strip("\n")]

                # update the line minus the extra contributors bits
                # Ex: `- This is my change text (#1234, #4567)
                line = f"{a}\n"
            new_file_contents += line

        # overwrite the file with the new format, without any contributor infornmation (for now)
        f.seek(0)
        f.write(new_file_contents)

        # create new section of Contributors at the bottom, if there are any
        if contributors:
            f.write("\nContributors:\n")
            for key, value in contributors.items():
                user = f"[@{key}](https://github.com/{key})"
                pr = ""
                for i in value:
                    pr += f" [#{i}](https://github.com/dbt-labs/dbt-core/pull/{i})"
                entry = f"{bullet} {user}{pr}\n"
                f.write(entry)


def main():
    try:
        version = sys.argv[1]
    except IndexError:
        raise Exception("A version is required.")

    format_contributors(version)
    print(f"Contributing section added to .changes/{version}.md.")


if __name__ == "__main__":
    main()
